# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.kaspawalletd_pb2 as kaspawalletd__pb2


class kaspawalletdStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/kaspawalletd.kaspawalletd/GetBalance',
                request_serializer=kaspawalletd__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=kaspawalletd__pb2.GetBalanceResponse.FromString,
                )
        self.CreateUnsignedTransactions = channel.unary_unary(
                '/kaspawalletd.kaspawalletd/CreateUnsignedTransactions',
                request_serializer=kaspawalletd__pb2.CreateUnsignedTransactionsRequest.SerializeToString,
                response_deserializer=kaspawalletd__pb2.CreateUnsignedTransactionsResponse.FromString,
                )
        self.ShowAddresses = channel.unary_unary(
                '/kaspawalletd.kaspawalletd/ShowAddresses',
                request_serializer=kaspawalletd__pb2.ShowAddressesRequest.SerializeToString,
                response_deserializer=kaspawalletd__pb2.ShowAddressesResponse.FromString,
                )
        self.NewAddress = channel.unary_unary(
                '/kaspawalletd.kaspawalletd/NewAddress',
                request_serializer=kaspawalletd__pb2.NewAddressRequest.SerializeToString,
                response_deserializer=kaspawalletd__pb2.NewAddressResponse.FromString,
                )
        self.Shutdown = channel.unary_unary(
                '/kaspawalletd.kaspawalletd/Shutdown',
                request_serializer=kaspawalletd__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=kaspawalletd__pb2.ShutdownResponse.FromString,
                )
        self.Broadcast = channel.unary_unary(
                '/kaspawalletd.kaspawalletd/Broadcast',
                request_serializer=kaspawalletd__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=kaspawalletd__pb2.BroadcastResponse.FromString,
                )
        self.Send = channel.unary_unary(
                '/kaspawalletd.kaspawalletd/Send',
                request_serializer=kaspawalletd__pb2.SendRequest.SerializeToString,
                response_deserializer=kaspawalletd__pb2.SendResponse.FromString,
                )
        self.Sign = channel.unary_unary(
                '/kaspawalletd.kaspawalletd/Sign',
                request_serializer=kaspawalletd__pb2.SignRequest.SerializeToString,
                response_deserializer=kaspawalletd__pb2.SignResponse.FromString,
                )


class kaspawalletdServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUnsignedTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowAddresses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_kaspawalletdServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=kaspawalletd__pb2.GetBalanceRequest.FromString,
                    response_serializer=kaspawalletd__pb2.GetBalanceResponse.SerializeToString,
            ),
            'CreateUnsignedTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUnsignedTransactions,
                    request_deserializer=kaspawalletd__pb2.CreateUnsignedTransactionsRequest.FromString,
                    response_serializer=kaspawalletd__pb2.CreateUnsignedTransactionsResponse.SerializeToString,
            ),
            'ShowAddresses': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowAddresses,
                    request_deserializer=kaspawalletd__pb2.ShowAddressesRequest.FromString,
                    response_serializer=kaspawalletd__pb2.ShowAddressesResponse.SerializeToString,
            ),
            'NewAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.NewAddress,
                    request_deserializer=kaspawalletd__pb2.NewAddressRequest.FromString,
                    response_serializer=kaspawalletd__pb2.NewAddressResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=kaspawalletd__pb2.ShutdownRequest.FromString,
                    response_serializer=kaspawalletd__pb2.ShutdownResponse.SerializeToString,
            ),
            'Broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.Broadcast,
                    request_deserializer=kaspawalletd__pb2.BroadcastRequest.FromString,
                    response_serializer=kaspawalletd__pb2.BroadcastResponse.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=kaspawalletd__pb2.SendRequest.FromString,
                    response_serializer=kaspawalletd__pb2.SendResponse.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=kaspawalletd__pb2.SignRequest.FromString,
                    response_serializer=kaspawalletd__pb2.SignResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kaspawalletd.kaspawalletd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class kaspawalletd(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kaspawalletd.kaspawalletd/GetBalance',
            kaspawalletd__pb2.GetBalanceRequest.SerializeToString,
            kaspawalletd__pb2.GetBalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUnsignedTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kaspawalletd.kaspawalletd/CreateUnsignedTransactions',
            kaspawalletd__pb2.CreateUnsignedTransactionsRequest.SerializeToString,
            kaspawalletd__pb2.CreateUnsignedTransactionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShowAddresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kaspawalletd.kaspawalletd/ShowAddresses',
            kaspawalletd__pb2.ShowAddressesRequest.SerializeToString,
            kaspawalletd__pb2.ShowAddressesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kaspawalletd.kaspawalletd/NewAddress',
            kaspawalletd__pb2.NewAddressRequest.SerializeToString,
            kaspawalletd__pb2.NewAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kaspawalletd.kaspawalletd/Shutdown',
            kaspawalletd__pb2.ShutdownRequest.SerializeToString,
            kaspawalletd__pb2.ShutdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kaspawalletd.kaspawalletd/Broadcast',
            kaspawalletd__pb2.BroadcastRequest.SerializeToString,
            kaspawalletd__pb2.BroadcastResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kaspawalletd.kaspawalletd/Send',
            kaspawalletd__pb2.SendRequest.SerializeToString,
            kaspawalletd__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kaspawalletd.kaspawalletd/Sign',
            kaspawalletd__pb2.SignRequest.SerializeToString,
            kaspawalletd__pb2.SignResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
